[build]
	base = "/"
	command = "hugo"
	publish = "public"
	[context.production.environment]
		HUGO_VERSION = "0.100.2"
[[headers]]
	for = "/*"
	[headers.values]
		Service-Worker-Allowed = "/"
[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404